import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const myFont = localFont({
  src:[
    {
     path: './fonts/RMNeueTRIAL-Light.woff',
     weight: '300',
     style: 'normal',
    },
    {
     path: './fonts/RMNeueTRIAL-Regular.woff',
     weight: '400',
     style: 'normal',
    },
    {
     path: './fonts/RMNeueTRIAL-Bold.woff',
     weight: '700',
     style: 'normal',
    }
  ]
}
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
